version: 2.1
orbs:
  node: circleci/node@2.0.1
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.1
      - node/test:
          version: 10.19.0